#ifndef ASL_COMMON_H
#define ASL_COMMON_H

// ShiftX3 CAN message IDs

#define ASL_SHIFTX3_BASE_ID  0xE3600
#define ASL_SHIFTX3_MAX_ID   ASL_SHIFTX3_BASE_ID + 0xFF

// notifications from ShiftX3

#define ASL_SHIFTX3_INF_ANNOUNCE  ASL_SHIFTX3_BASE_ID
#define ASL_SHIFTX3_INF_STATS     ASL_SHIFTX3_BASE_ID + 2
#define ASL_SHIFTX3_INF_BUTTON    ASL_SHIFTX3_BASE_ID + 60

// set messages to send to ShiftX3

#define ASL_SHIFTX3_SET_CONFIG      ASL_SHIFTX3_BASE_ID + 3
#define ASL_SHIFTX3_SET_DISPLAY     ASL_SHIFTX3_BASE_ID + 50
#define ASL_SHIFTX3_SET_LED         ASL_SHIFTX3_BASE_ID + 10
#define ASL_SHIFTX3_SET_ALERT       ASL_SHIFTX3_BASE_ID + 20
#define ASL_SHIFTX3_SET_ALRT_THRSH  ASL_SHIFTX3_BASE_ID + 21
#define ASL_SHIFTX3_SET_ALRT_VAL    ASL_SHIFTX3_BASE_ID + 22

#endif