name=MicrocanAsl
version=1.0.0
author=microcan
maintainer=microcan
sentence=A library for AutoSport Labs TireX and ShiftX3.
paragraph=Use TireX sensors and the ShiftX3 module in Arduino
category=Device Control
url=http://github.com/microcan/Arduino
architectures=esp32
includes=MicrocanAsl.h