name=Microcan
version=1.0.0
author=microcan
maintainer=microcan
sentence=Basic and common functions for Microcan libraries.
paragraph=A common library used by MicrocanAsl and MicrocanGauges
category=Other
url=http://github.com/microcan/Arduino
architectures=*
includes=Microcan.h