name=MicrocanGauges
version=1.0.0
author=microcan
maintainer=microcan
sentence=A library for M5 display of automotive style gauges.
paragraph=Draw analogue guages, tire patches and more.
category=Display
url=http://github.com/microcan/Arduino
architectures=esp32
depends=M5Unified, Microcan
includes=MicrocanGauges.h